spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:57528;databaseName=milktea;encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:Password123!}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    vn.edu.ute.milktea: DEBUG
    org.springframework.security: INFO
