package vn.edu.ute.milktea.common;

public enum ErrorCode {
    VALIDATION_FAILED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    ACCESS_DENIED,
    CSRF_INVALID,
    TABLE_NOT_FOUND,
    QR_INVALID,
    TABLE_SESSION_CLOSED,
    TABLE_SESSION_CHANGED,
    CART_VERSION_CONFLICT,
    TABLE_CLOSE_NOT_ALLOWED,
    PRODUCT_UNAVAILABLE,
    ORDER_STATE_CONFLICT,
    CANCELLATION_PENDING,
    PAYMENT_ALREADY_RECORDED,
    REFUND_NOT_APPROVED,
    INVENTORY_INSUFFICIENT,
    IDEMPOTENCY_CONFLICT,
    IMAGE_UPLOAD_FAILED,
    INTERNAL_ERROR
}
